site_name: API Logic Server
docs_dir: api_logic_server_cli/docs
theme:
  name: material
  theme:
  features:
    - navigation.instant
    - kramdown
    - content.tooltips
nav:
  - " ": index.md
  - 0. Quick Start:
    - Install API Logic Server: Install.md
    - "Create an API Logic Project": Create-ApiLogicProject.md
    - Execute an API Logic Project: Execute.md
    - "Tutorial": Tutorial.md
  - 1. Admin Web App:
    - "Admin App Features": "Admin-Tour.md"
    - Admin-Customization.md
  - 2. API:
    - "JSON:API": API.md
    - "API Customization": API-Customize.md
  - 3. Logic:
    - "Rules; 40X, Extensible": Logic-Why.md
    - "Rules": Logic.md
    - "Logic Operation": "Logic-Operation.md"
    - "TDD-based Approach": "Logic-Tutorial.md"
  - Database:
    - Data-Model-Classes.md
    - Data-Model-Customization.md
    - "Connection Examples": Database-Connectivity.md
    - "Install pyodbc: SqlServer": Install-pyodbc.md
    - Sample-Database.md
  - Using your IDE:
    - "Open and Execute": IDE-Execute.md
    - "Customize": IDE-Customize.md
  - Managing API Logic Projects:
    - "Structure": Project-Structure.md
    - "Rebuild": Project-Rebuild.md
    - "Working With Docker": Working-With-Docker.md
    - "Virtual Environment": Project-Env.md
    - "Execution": Project-Execution.md
    - "Builders": Project-Builders.md
  - Testing:
    - "Testing With Behave": Behave.md
    - "Behave Logic Report": Behave-Logic-Report.md
  - Architecture:
    - "What is API Logic Server": Architecture-What-Is.md
    - Architecture.md
    - Working-with-the-Admin-App.md
    - Working-with-Flask-AppBuilder.md
    - "API Logic Server Development": Internals.md
  - Troubleshooting.md
  - FAQs:
    - "Is this a RETE Engine": FAQ-RETE.md
    - "Is this a Low Code approach?": FAQ-Low-Code.md
  - Tech Notes:
    - "About Tech Notes": Tech--Notes.md
    - "Docker": Tech-Docker.md
    - "Python for a Java developer": Tech-Python.md
    - "Is API Logic Server a 4L": Tech-4GL.md
    - "Python Installation": Tech-Install-Python.md
    - "Mkdocs Material": Tech-mkdocs-material.md
    - "CodeSpaces": Tech-CodeSpaces.md
  - Unused:
    - "zz Logic = Rules + Python": "Logic-Rules-plus-Python.md"
    - "Old Quick Start": Quick-Start.md
markdown_extensions:
  - toc:
      baselevel: 2
      title: On this Page
      toc_depth: 5
  - meta
  - attr_list
  - abbr
  - footnotes
  - md_in_html
  - pymdownx.emoji:
      title: "long"
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
