site_name: API Logic Server
theme:
  name: material
  features:
    - navigation.instant
nav:
  - " ": index.md
  - Quick Start:
    - Install API Logic Server:
      - "Install Options": Install.md
      - "Using Docker": Install-With-Docker.md
      - "Using local install": Install-Locally.md
      - "Using PythonAnyWhere": Install-PythonAnywhere.md
      - "Installation Notes": Install-Notes.md
    - "Create an API Logic Project": Create-ApiLogicProject.md
    - Execute an API Logic Project:
      - "Execution Options": Execute.md
      - "From Command Line": Execute-Command-Line.md
      - "From VSCode Local": Execute-VSCode-Local.md
      - "From VSCode Docker": Execute-VSCode-Docker.md
      - "From Pycharm": Execute-PyCharm-Local.md
    - "Tutorial": Tutorial.md
    - Sample-Database.md
    - "Working With Docker": Working-With-Docker.md
  - 1. Admin Web App:
    - "Admin App Features": "Admin-Tour.md"
    - Admin-Customization.md
  - 2. API:
    - "JSON:API": API.md
    - "API Customization": API-Customize.md
  - 3. Unique Backend Logic:
    - "Why Rules": Logic-Why.md
    - "Rules; 40X, Extensible": Logic.md
    - "Logic Operation": "Logic-Operation.md"
    - "TDD-based Approach": "Logic-Tutorial.md"
  - Testing:
    - "Testing With Behave": Behave.md
    - "Behave Logic Report": Behave-Logic-Report.md
  - Managing API Logic Projects:
    - "Structure": Project-Structure.md
    - "Rebuild": Project-Rebuild.md
    - "Virtual Environment": Project-Env.md
    - "Execution": Project-Execution.md
    - "Builders": Project-Builders.md
  - Database Access:
    - "Connection Examples": Database-Connectivity.md
    - "Install pyodbc: SqlServer": Install-pyodbc.md
    - Data-Model-Classes.md
    - Data-Model-Customization.md
  - Architecture:
    - Architecture.md
    - Working-with-the-Admin-App.md
    - Working-with-Flask-AppBuilder.md
    - "API Logic Server Development": Internals.md
  - Troubleshooting.md
  - Unused:
    - "zz Logic = Rules + Python": "Logic-Rules-plus-Python.md"
    - "Old Quick Start": Quick-Start.md
    - _Footer.md
markdown_extensions:
  - toc:
      baselevel: 2
      title: On this Page
      toc_depth: 5
  - meta
  - attr_list
  - pymdownx.emoji:
      title: "long"
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
